inherit_gem:
  bunto: .rubocop.yml

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - bunto-seo-tag.gemspec

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

AllCops:
  Exclude:
    - vendor/**/*
