inherit_gem:
  bunto: .rubocop.yml

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - bunto-seo-tag.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/IndentHeredoc:
  Exclude:
    - spec/**/*

AllCops:
  Exclude:
    - vendor/**/*
