rvm:
  - 2.2.3
before_install:
  - gem install bundler
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - chmod a+x script/release
  - chmod a+x script/site
language: ruby
script: script/cibuild
sudo: false
cache: bundler
